Define a Dockerfile
google/tsunami-security-scanner pull request #20
Opened 2020-07-09 19:48 UTC by rayanht

#18

2020-07-09 19:53 UTC, rayanht commented
An alternative to this Dockerfile could simply run the `quick_start.sh` but my motivation is that this is a lot more clearer and maintanable.

2020-07-09 20:01 UTC, rayanht commented
@googlebot I signed it!

2020-07-10 00:56 UTC, JonZeolla commented
This cannot work as currently documented because `127.0.0.1` in the container does not refer to `127.0.0.1` on the host.  Consider setting up a docker network, or something with compose.  The docker network approach would be something like:
```bash
docker network create example
docker run --network example --name unauthenticated-jupyter-notebook -p 8888:8888 -d jupyter/base-notebook start-notebook.sh --NotebookApp.token=''
docker run --network example tsunami java -cp "/usr/tsunami/tsunami-main-0.0.2-SNAPSHOT-cli.jar:/usr/tsunami/plugins/*" -Dtsunami-config.location=/usr/tsunami/tsunami.yaml com.google.tsunami.main.cli.TsunamiCli --hostname-target=unauthenticated-jupyter-notebook
```

Minor other feedback:
- Suggest updating the `TARGET_IP` approach to differentiate between v4 and v6 and adding support for `--hostname-target` (see [this](https://github.com/google/tsunami-security-scanner/blob/6314ba862884833be797e7e40d97c5b2cfc32101/main/src/main/java/com/google/tsunami/main/cli/option/ScanTargetCliOptions.java#L32-L45))
- Consider using a combination of `ENTRYPOINT` and `CMD` to allow arguments to be overridden to the defined base command at `docker run`.  Something like the following would allow a simplification of the docker network example's last command to `docker run --network example tsunami -Dtsunami-config.location=/usr/tsunami/tsunami.yaml com.google.tsunami.main.cli.TsunamiCli --hostname-target=unauthenticated-jupyter-notebook`
    ```
    ENTRYPOINT ["java", "-cp", "/usr/tsunami/tsunami-main-0.0.2-SNAPSHOT-cli.jar:/usr/tsunami/plugins/*"]
    CMD -Dtsunami-config.location=/usr/tsunami/tsunami.yaml com.google.tsunami.main.cli.TsunamiCli --ip-v4-target=$TARGET_IP 
    ```

Note:  I'm not affiliated with this project or Google, just giving some feedback...

2020-07-10 07:08 UTC, rayanht commented
@JonZeolla Thanks for the suggestions! Re: the docker network, how about simply running the Tsunami image with `--network="host"` ? This would allow to scan for vulnerabilities in applications that aren't necessarily docker images themselves.

2020-07-10 10:09 UTC, vdjagilev commented
Have a little side note for this one.

I am not sure how `gradle` defines a version for any particular `.jar` file it creates. But in this case `tsunami-main-0.0.2-SNAPSHOT-cli.jar` is hardcoded into Dockerfile. I think it would be good if there is no need to change `Dockerfile` each time when jar file name is different. 

Maybe it's possible to do something like this `JARFILE=$(find ...)`, I think this would be good example https://github.com/google/tsunami-security-scanner/blob/master/quick_start.sh#L57

2020-07-10 10:11 UTC, rayanht commented
@vdjagilev I considered it but I wasn't aware of the `basename` command. Will definitely amend, thank you for the heads up!

2020-07-10 15:00 UTC, rayanht commented
A bit of an update on this, there is no way to persist variables between RUN commands in Docker and I can't seem to get string interpolation to behave nicely inside the ENTRYPOINT. 

To be honest, I don't really see the point in specifying the version number in the filename of the generated jar. Could we perhaps drop it and have a standard filename?

2020-07-10 15:39 UTC, JonZeolla commented
How I've solved this in the past is to use a build arg (`ARG`), and then use something like a `Makefile` or wrapper shell script that grabs the version [from the project](https://github.com/google/tsunami-security-scanner/blob/6314ba862884833be797e7e40d97c5b2cfc32101/build.gradle#L16) and passes it into the `docker build` via an arg.

While its a completely different project and context, here is a [concrete example](https://github.com/SeisoLLC/easy_sast/blob/master/Makefile#L46-L47)

2020-07-10 15:41 UTC, rayanht commented
@JonZeolla Yep that would definitely work, it's just that I would've preferred a fully self-contained Docker image that the end user could simply `docker run`

2020-07-10 15:46 UTC, JonZeolla commented
What about just finding the jar at build time and rename it to a standard name like `tsunami-main-cli.jar` and use that in the `ENTRYPOINT`?

2020-07-10 16:06 UTC, rayanht commented
@JonZeolla ...it's so obvious that I didn't think about it 😅

2020-07-10 16:24 UTC, vdjagilev commented
Maybe it's better to leave old documentation and divide installation approaches into 2 topics (with docker and without docker)? Use case: Running docker in VM with Kali Linux can be memory-expensive

2020-12-08 21:26 UTC, magl0 requested changes

2020-12-08 21:26 UTC, magl0 commented on Dockerfile
> +CMD ["--ip-v4-target=127.0.0.1", "--scan-results-local-output-format=JSON", "--scan-results-local-output-filename=logs/tsunami-output.json"]
nit: per code style, please add a new line at the end of this file.

2020-12-09 11:01 UTC, merged